# Generated by Django 4.2 on 2023-05-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
