# Generated by Django 4.2 on 2023-05-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
